### ISSUE TITLE
Looking forward to the code release.

### ISSUE THREAD

**Issue by whuhxb** [shenglandu/PushBoundary#1]
Hi,

   I'm looking forward to the code release of this good work. Thanks a lot.
   Best wishes.

Xiaobing

**Comment by shenglandu** [comment]
> Hi,
> 
> I'm looking forward to the code release of this good work. Thanks a lot. Best wishes.
> 
> Xiaobing

Hi! Thank you for your interest. We will release the code soon.

Best,
Shenglan

**Comment by whuhxb** [comment]
Hi @shenglandu 

When will the code be released? Thanks again.

**Comment by shenglandu** [comment]
> Hi @shenglandu
> 
> When will the code be released? Thanks again.

Hi! We estimate to release the code/data before the end of this February. 


Best Regards,
Shenglan

**Comment by shenglandu** [comment]
> Hi @shenglandu
> 
> When will the code be released? Thanks again.

Hi Xiaobing, 

the code for S3DIS segmentation is released. Feel free to contact me if you have any questions regarding the code.

Best,
Shenglan
