### ISSUE TITLE
关于sent数据集的问题

### ISSUE THREAD

**Issue by sanfenzhongmeichifanle** [shenglandu/PushBoundary#10]
您好，我现在走到sent数据集的测试阶段了，但是我发现测试完成以后，并没有评价指标的数据？
所以您的代码部分并没有进行这方面的输出吗？

**Comment by shenglandu** [comment]
你好，

Sensat testset不提供标签，所以无法线下测试性能，需要把你的结果上传到官网在线验证性能。具体可查看https://github.com/shenglandu/PushBoundary/issues/7

**Comment by sanfenzhongmeichifanle** [comment]
原来是这样，转牛角尖了，忘记这茬了，谢谢您

**Comment by sanfenzhongmeichifanle** [comment]
![image](https://github.com/shenglandu/PushBoundary/assets/133829083/276ae47c-6e31-46f8-8e2a-b01f57c7e1d5)
您好，您的边界处理的脚本代码当中，怎么没有涉及到dis_boundary？这是为什么？我很是迷惑？

**Comment by shenglandu** [comment]
> ![image](https://private-user-images.githubusercontent.com/133829083/329682034-276ae47c-6e31-46f8-8e2a-b01f57c7e1d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MDMzOTIsIm5iZiI6MTcxNTYwMzA5MiwicGF0aCI6Ii8xMzM4MjkwODMvMzI5NjgyMDM0LTI3NmFlNDdjLTZlMzEtNDZmOC04ZTJhLWIwMWY1N2M3ZTFkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxMjI0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODUwNDkyZWNkZDE3NTUwNzFhMGE4NDFiZThhM2I4YTQxZTU2NmM2M2U4MWEzZjg4ZDVkODJmMTFkYmM4MzNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cOBzg_vVsUXEgXsLHUygst0NSh_43a7LXX0BndgiTfU) 您好，您的边界处理的脚本代码当中，怎么没有涉及到dis_boundary？这是为什么？我很是迷惑？

你好，在实验中我发现dis_boundary对效果提升不明显，所以最后没有使用这个信息。
