### ISSUE TITLE
how to apply this algorithm on my own dataset

### ISSUE THREAD

**Issue by cainiaoshidai** [shenglandu/PushBoundary#2]
Hi,
    It's an excellent job.  Now I want to apply it to my own dataset. But I don't know how to get `dis_boundary` and `is_boundary`. 
    Can you release your data-preparing code?
    Thanks very much.
Best.

**Comment by shenglandu** [comment]
> Hi, It's an excellent job. Now I want to apply it to my own dataset. But I don't know how to get `dis_boundary` and `is_boundary`. Can you release your data-preparing code? Thanks very much. Best.

Hi!

Thank you for your interest in our work. Sure, I can clean and release the pre-processing codes in the coming days. 

We simply use knn search to retrieve each point and check if it shares the same semantic label as all of its neighbors. You only need to do this for the training set. In case you have a larger dataset, you might consider using different sizes of neighborhoods and using C++ to speed up the computation.


Best,
Shenglan

**Comment by cainiaoshidai** [comment]
> 

Thanks. I think I can solve this problem. 
Best.

**Comment by cainiaoshidai** [comment]
Hi,
   I have encountered a new problem. The direction of each class is from the boundary point to that point. But how should the direction of the boundary be defined?

**Comment by shenglandu** [comment]
> Hi, I have encountered a new problem. The direction of each class is from the boundary point to that point. But how should the direction of the boundary be defined?

Hi!

The direction of the boundary is defined as (0,0,0), which means that at boundaries the direction has a zero norm, while at interior regions the direction has a norm of 1. We empirically observed some improvements brought by such a design (as reported in the paper). However, I am not sure if this is optimal. I think you can try various designs of the directions to see which fits your task and brings the most improvement.

Best Regards,
Shenglan

**Comment by cainiaoshidai** [comment]
Thanks very much. I will have a try.
Best.

**Comment by cainiaoshidai** [comment]
Hi,
    I successfully ran your code on the S3DIS dataset. I get 67.3% IoU on area_5. But I found that where the boundary point prediction is correct, the semantic segmentation boundary is fine. It seems that the prediction of boundary points largely affects the results of semantic segmentation. I want to get a more stable boundary, especially the boundary of the wall.
Can you give me some advice?
Thanks.
Best.

**Comment by shenglandu** [comment]
> Hi, I successfully ran your code on the S3DIS dataset. I get 67.3% IoU on area_5. But I found that where the boundary point prediction is correct, the semantic segmentation boundary is fine. It seems that the prediction of boundary points largely affects the results of semantic segmentation. I want to get a more stable boundary, especially the boundary of the wall. Can you give me some advice? Thanks. Best.

Hi,

Yes indeed, the task of boundary detection correlates with the task of semantic segmentation. In our future work, I mentioned the adaptive boundary detection method [Investigate indistinguishable points in semantic segmentation of 3d point cloud, AAAI 2021] can be explored for better boundary detection. You can have a try if you are interested. You can also adjust the classification weight between boundary and interior points, which is currently set as 0.6:0.4.

Best Regards,
Shenglan

**Comment by cainiaoshidai** [comment]
Thanks for your reply and advice.  I will have a try. 
Best.

**Comment by LinLin1031** [comment]
> 
> Hi!
> 
> Thank you for your interest in our work. Sure, I can clean and release the pre-processing codes in the coming days.
> 
> We simply use knn search to retrieve each point and check if it shares the same semantic label as all of its neighbors. You only need to do this for the training set. In case you have a larger dataset, you might consider using different sizes of neighborhoods and using C++ to speed up the computation.
> 
> Best, Shenglan

May I ask if you could share the code for this algorithm with me? I understand your thoughts, but I still don't have a clue.

**Comment by LinLin1031** [comment]
@shenglandu I am looking for your help.

**Comment by shenglandu** [comment]
> @shenglandu I am looking for your help.

Hello there,

Sure, I can upload the pre-processing code this week.


Best Regards,
Shenglan

**Comment by LinLin1031** [comment]
> > @shenglandu I am looking for your help.
> 
> Hello there,
> 
> Sure, I can upload the pre-processing code this week.
> 
> Best Regards, Shenglan

Thank you for your upcoming sharing, and I would greatly appreciate your help.

**Comment by shenglandu** [comment]
> > > @shenglandu I am looking for your help.
> > 
> > 
> > Hello there,
> > Sure, I can upload the pre-processing code this week.
> > Best Regards, Shenglan
> 
> Thank you for your upcoming sharing, and I would greatly appreciate your help.

Hi Linlin,

No worries. The updated pre-processing code is attached [here](https://github.com/shenglandu/PushBoundary/blob/main/KPConv_Backbone/preprocessing_boundaries.py). 


Best Regards,
Shenglan

**Comment by LinLin1031** [comment]
@shenglandu Hello! Do you need to provide additional preprocessing code to generate the "KDTree.pkl" file?

**Comment by LinLin1031** [comment]
> @shenglandu Hello! Do you need to provide additional preprocessing code to generate the "KDTree.pkl" file?

@shenglandu 
Is the preprocessing code for this step the same as [the preprocessing code used by RandLA-Net](https://github.com/QingyongHu/RandLA-Net/blob/master/utils/data_prepare_semantic3d.py)? If it's the same, I'll just use it.

**Comment by shenglandu** [comment]
> > @shenglandu Hello! Do you need to provide additional preprocessing code to generate the "KDTree.pkl" file?
> 
> @shenglandu Is the preprocessing code for this step the same as [the preprocessing code used by RandLA-Net](https://github.com/QingyongHu/RandLA-Net/blob/master/utils/data_prepare_semantic3d.py)? If it's the same, I'll just use it.

Hello,

Generating "kdtree.pkl" is not necessary. "Preprocessing_boundaries.py" is used to generate boundaries and directions per point. The code is not the same as used in Randla-Net.

Best Regards,
Shenglan

**Comment by LinLin1031** [comment]
> > > @shenglandu Hello! Do you need to provide additional preprocessing code to generate the "KDTree.pkl" file?
> > 
> > 
> > @shenglandu Is the preprocessing code for this step the same as [the preprocessing code used by RandLA-Net](https://github.com/QingyongHu/RandLA-Net/blob/master/utils/data_prepare_semantic3d.py)? If it's the same, I'll just use it.
> 
> Hello,
> 
> Generating "kdtree.pkl" is not necessary. "Preprocessing_boundaries.py" is used to generate boundaries and directions per point. The code is not the same as used in Randla-Net.
> 
> Best Regards, Shenglan


https://github.com/shenglandu/PushBoundary/blob/24e1d965a94c74cb1526517b8bfc4eb1510728b0/KPConv_Backbone/datasets/SensatUrban_boundary.py#L124

@shenglandu  Do you mean this line can be annotated?

**Comment by shenglandu** [comment]
> > > > @shenglandu Hello! Do you need to provide additional preprocessing code to generate the "KDTree.pkl" file?
> > > 
> > > 
> > > @shenglandu Is the preprocessing code for this step the same as [the preprocessing code used by RandLA-Net](https://github.com/QingyongHu/RandLA-Net/blob/master/utils/data_prepare_semantic3d.py)? If it's the same, I'll just use it.
> > 
> > 
> > Hello,
> > Generating "kdtree.pkl" is not necessary. "Preprocessing_boundaries.py" is used to generate boundaries and directions per point. The code is not the same as used in Randla-Net.
> > Best Regards, Shenglan
> 
> https://github.com/shenglandu/PushBoundary/blob/24e1d965a94c74cb1526517b8bfc4eb1510728b0/KPConv_Backbone/datasets/SensatUrban_boundary.py#L124
> 
> @shenglandu Do you mean this line can be annotated?

Hi,

I'm confused now:fearful: Can you specify more details about the problem you wish to solve? For example, the data you are using (S3DIS, SensatUrban, or your own dataset), and which step it gives an error?
- for generating GT boundaries and directions, you can use the code [here](https://github.com/shenglandu/PushBoundary/blob/24e1d965a94c74cb1526517b8bfc4eb1510728b0/KPConv_Backbone/preprocessing_boundaries.py).
- for organizing the data as input batches, I don't think you need to comment any functions in the script. In case you use your own data, you may need to slightly modify the code to adjust to your data. 

I am re-opening the issue now. Feel free to let me know if there is a specific error you want to tackle in your training and I can try to help.

Best Regards,
Shenglan

**Comment by LinLin1031** [comment]
> Hi,
> 
> I'm confused now😨 Can you specify more details about the problem you wish to solve? For example, the data you are using (S3DIS, SensatUrban, or your own dataset), and which step it gives an error?
> 
> * for generating GT boundaries and directions, you can use the code [here](https://github.com/shenglandu/PushBoundary/blob/24e1d965a94c74cb1526517b8bfc4eb1510728b0/KPConv_Backbone/preprocessing_boundaries.py).
> * for organizing the data as input batches, I don't think you need to comment any functions in the script. In case you use your own data, you may need to slightly modify the code to adjust to your data.
> 
> I am re-opening the issue now. Feel free to let me know if there is a specific error you want to tackle in your training and I can try to help.
> 
> Best Regards, Shenglan

Thank you for your patience. The dataset I used is a custom dataset, which is organized similarly to SensatUrban (several ply files). I am experiencing the following problem:
![image](https://github.com/shenglandu/PushBoundary/assets/50825626/998ac571-b3dc-4bc5-917a-2feeacd605da)

The "Please use the preprocessed subsampled point clouds" makes me think that the "kdtree.pkl" file must be generated and used. @shenglandu

**Comment by LinLin1031** [comment]
@shenglandu Can you respond to my question at your convenience? Thank you very much!

**Comment by shenglandu** [comment]
> > Hi,
> > I'm confused now😨 Can you specify more details about the problem you wish to solve? For example, the data you are using (S3DIS, SensatUrban, or your own dataset), and which step it gives an error?
> > 
> > * for generating GT boundaries and directions, you can use the code [here](https://github.com/shenglandu/PushBoundary/blob/24e1d965a94c74cb1526517b8bfc4eb1510728b0/KPConv_Backbone/preprocessing_boundaries.py).
> > * for organizing the data as input batches, I don't think you need to comment any functions in the script. In case you use your own data, you may need to slightly modify the code to adjust to your data.
> > 
> > I am re-opening the issue now. Feel free to let me know if there is a specific error you want to tackle in your training and I can try to help.
> > Best Regards, Shenglan
> 
> Thank you for your patience. The dataset I used is a custom dataset, which is organized similarly to SensatUrban (several ply files). I am experiencing the following problem: ![image](https://user-images.githubusercontent.com/50825626/265474564-998ac571-b3dc-4bc5-917a-2feeacd605da.png)
> 
> The "Please use the preprocessed subsampled point clouds" makes me think that the "kdtree.pkl" file must be generated and used. @shenglandu

Hello,

Sorry for the late response due to the (possible) time difference. 

I see that you use "SensatUrban_boundary.py" to process your data. When I ran the Sensat experiments for my paper, I first downsampled the original point clouds and then generated GT boundaries/directions from downsampled point clouds. This was time-wise more efficient than the other way around. Therefore, in the function "load_subsampled_points", I skipped the grid subsampling part. I think this leads to the tree error in your screenshot. For more code details, please check the difference between [s3dis subsampling](https://github.com/shenglandu/PushBoundary/blob/main/KPConv_Backbone/datasets/S3DIS_boundary.py#L318) and [sensat subsampling](https://github.com/shenglandu/PushBoundary/blob/main/KPConv_Backbone/datasets/SensatUrban_boundary.py#L355).

Can you try to use the s3dis preprocessing code instead, or simply replace the function "load_subsampled_points" with what was used in "S3DIS_boundary.py"? I think if your code executes the grid subsampling, the kdtree files will be automatically generated and thus the error can be avoided. Can you try it and let me know if it works?


Best,
Shenglan

**Comment by LinLin1031** [comment]
> Hello,
> 
> Sorry for the late response due to the (possible) time difference.
> 
> I see that you use "SensatUrban_boundary.py" to process your data. When I ran the Sensat experiments for my paper, I first downsampled the original point clouds and then generated GT boundaries/directions from downsampled point clouds. This was time-wise more efficient than the other way around. Therefore, in the function "load_subsampled_points", I skipped the grid subsampling part. I think this leads to the tree error in your screenshot. For more code details, please check the difference between [s3dis subsampling](https://github.com/shenglandu/PushBoundary/blob/main/KPConv_Backbone/datasets/S3DIS_boundary.py#L318) and [sensat subsampling](https://github.com/shenglandu/PushBoundary/blob/main/KPConv_Backbone/datasets/SensatUrban_boundary.py#L355).
> 
> Can you try to use the s3dis preprocessing code instead, or simply replace the function "load_subsampled_points" with what was used in "S3DIS_boundary.py"? I think if your code executes the grid subsampling, the kdtree files will be automatically generated and thus the error can be avoided. Can you try it and let me know if it works?
> 
> Best, Shenglan

Thank you for your reply. My understanding is that the downsampling was supposed to be done before the preprocessing to generate the boundary labels, which would indeed reduce a great deal of unnecessary boundary label computation time.

But I didn't do that, so I need to copy the downsampling code from "S3DIS_boundary.py" to "SensatUrban_boundary.py", and then run "train_SensatUrban_boundary.py" to do the downsampling and training.

**Comment by LinLin1031** [comment]
Do I only need to downsample the training set and validation set with boundary label generation? The test set doesn't need to be manipulated in any way?

**Comment by shenglandu** [comment]
> Do I only need to downsample the training set and validation set with boundary label generation? The test set doesn't need to be manipulated in any way?

Hello,

Test set still needs to be downsampled. The purpose of downsampling is to reduce the density of point clouds since networks usually cannot consume massive points. 

Do you have GT boundaries and directions for your test set? If so, using [this function](https://github.com/shenglandu/PushBoundary/blob/main/KPConv_Backbone/datasets/S3DIS_boundary.py#L318) would help you automatically downsample the files, generate kdtree files, and continue training. Otherwise, I would recommend you to first downsample the test set, generate corresponding kdtree files, organize the files in your data folder, and then run [this function](https://github.com/shenglandu/PushBoundary/blob/main/KPConv_Backbone/datasets/SensatUrban_boundary.py#L355).

Best,
Shenglan

**Comment by LinLin1031** [comment]
![微信图片编辑_20230906092735](https://github.com/shenglandu/PushBoundary/assets/50825626/f8118b9d-e0de-4f7b-830b-dcd28b90e18c)

I ran it again after downsampling and got the above error.

**Comment by shenglandu** [comment]
> ![微信图片编辑_20230906092735](https://user-images.githubusercontent.com/50825626/265864076-f8118b9d-e0de-4f7b-830b-dcd28b90e18c.jpg)
> 
> I ran it again after downsampling and got the above error.

Hi,

Have you followed [compiling steps](https://github.com/shenglandu/PushBoundary#installation) to compile the wrappers?

Best,
Shenglan

**Comment by LinLin1031** [comment]
> Hi,
> 
> Have you followed [compiling steps](https://github.com/shenglandu/PushBoundary#installation) to compile the wrappers?
> 
> Best, Shenglan

![image](https://github.com/shenglandu/PushBoundary/assets/50825626/ab973c5e-ebb3-4a0b-b8ea-3bde25f658c3)

Yes, I do. And no errors are reported when running "sh compile_wrappers.sh".

And in the last screenshot, the first few lines of output indicate that I don't have the "batch_limits.pkl" and "neighbors_limits.pkl" files. I searched all the files and did not find the code to generate these files.

**Comment by LinLin1031** [comment]
And in the last screenshot, the first few lines of output indicate that I don't have the "batch_limits.pkl" and "neighbors_limits.pkl" files. I searched all the files and did not find the code to generate these files.

**Comment by shenglandu** [comment]
> And in the last screenshot, the first few lines of output indicate that I don't have the "batch_limits.pkl" and "neighbors_limits.pkl" files. I searched all the files and did not find the code to generate these files.

The ".pkl" files are generated in the function ["calibration"](https://github.com/shenglandu/PushBoundary/blob/main/KPConv_Backbone/datasets/SensatUrban_boundary.py#L611). Your error indicates that when the data are retrieved as batches, the neighborhood searching function can not be found. This is weird since you have compiled the wrappers. Can you show me a screenshot of your folder "cpp_wrappers/cpp_neighbours"?

Can you also try deleting what was compiled there and then recompile it?

**Comment by LinLin1031** [comment]
> > And in the last screenshot, the first few lines of output indicate that I don't have the "batch_limits.pkl" and "neighbors_limits.pkl" files. I searched all the files and did not find the code to generate these files.
> 
> The ".pkl" files are generated in the function ["calibration"](https://github.com/shenglandu/PushBoundary/blob/main/KPConv_Backbone/datasets/SensatUrban_boundary.py#L611). Your error indicates that when the data are retrieved as batches, the neighborhood searching function can not be found. This is weird since you have compiled the wrappers. Can you show me a screenshot of your folder "cpp_wrappers/cpp_neighbours"?
> 
> Can you also try deleting what was compiled there and then recompile it?

![image](https://github.com/shenglandu/PushBoundary/assets/50825626/dd3ed2be-f327-4911-a17e-1f0de4f5c950)

I tried your suggestion before, I removed the cpp_wrapper, replaced it with the source code and recompiled it still with this error.

Can the ".pkl" files be generated in the function ["calibration"](https://github.com/shenglandu/PushBoundary/blob/main/KPConv_Backbone/datasets/SensatUrban_boundary.py#L611)? This function seems to only read the file, the variables "neighbor_lim_dict" and "batch_lim_dict" are null.

**Comment by shenglandu** [comment]
> > > And in the last screenshot, the first few lines of output indicate that I don't have the "batch_limits.pkl" and "neighbors_limits.pkl" files. I searched all the files and did not find the code to generate these files.
> > 
> > 
> > The ".pkl" files are generated in the function ["calibration"](https://github.com/shenglandu/PushBoundary/blob/main/KPConv_Backbone/datasets/SensatUrban_boundary.py#L611). Your error indicates that when the data are retrieved as batches, the neighborhood searching function can not be found. This is weird since you have compiled the wrappers. Can you show me a screenshot of your folder "cpp_wrappers/cpp_neighbours"?
> > Can you also try deleting what was compiled there and then recompile it?
> 
> ![image](https://user-images.githubusercontent.com/50825626/266004003-dd3ed2be-f327-4911-a17e-1f0de4f5c950.png)
> 
> I tried your suggestion before, I removed the cpp_wrapper, replaced it with the source code and recompiled it still with this error.
> 
> Can the ".pkl" files be generated in the function ["calibration"](https://github.com/shenglandu/PushBoundary/blob/main/KPConv_Backbone/datasets/SensatUrban_boundary.py#L611)? This function seems to only read the file, the variables "neighbor_lim_dict" and "batch_lim_dict" are null.

Regarding calibration, I think yes, ".pkl" files are generated from there. Please double-check code details about that if you are interested.
Regarding compiling, do you use Windows to compile? The framework was tested on Ubuntu. If you use Windows, please refer to the official KP-Conv implementation [install guide](https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/master/INSTALL.md). 
Since my experiments were conducted on Ubuntu, I cannot offer you more help on how to compile on Windows. Sorry for that:frowning_face:.

**Comment by LinLin1031** [comment]
> Regarding calibration, I think yes, ".pkl" files are generated from there. Please double-check code details about that if you are interested. Regarding compiling, do you use Windows to compile? The framework was tested on Ubuntu. If you use Windows, please refer to the official KP-Conv implementation [install guide](https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/master/INSTALL.md). Since my experiments were conducted on Ubuntu, I cannot offer you more help on how to compile on Windows. Sorry for that☹️.

Sorry, I still didn't understand in the calibration function that it can create "batch_limits.pkl" and "neighbors_limits.pkl" files. I'm using CentOS in a cluster, I'll try to create a new virtual environment and see if it works.

**Comment by LinLin1031** [comment]
I have solve the question mentioned above. Thank you.
