### ISSUE TITLE
How the modified S3DIS dataset in the paper was constructed

### ISSUE THREAD

**Issue by wu546300070** [shenglandu/PushBoundary#6]
Thank you for your outstanding work！❤️I am a little confused about your dataset (S3DIS) and how it went from the original XYZRGB only to the 14 dimensional data you mentioned（Normal,[nx, ny, nz], Boundary[0,1],Direction[dx, dy, dz]）. 

I mean how does the dataset downloaded from the official website become the dataset in your paper and how is this process realized? Could you provide the code?🥹

Best Regards,
Yeechao

**Comment by shenglandu** [comment]
> Thank you for your outstanding work！❤️I am a little confused about your dataset (S3DIS) and how it went from the original XYZRGB only to the 14 dimensional data you mentioned（Normal,[nx, ny, nz], Boundary[0,1],Direction[dx, dy, dz]）.
> 
> I mean how does the dataset downloaded from the official website become the dataset in your paper and how is this process realized? Could you provide the code?🥹
> 
> Best Regards, Yeechao

Hello Yeechao,

Thank you for your interest in our work:smiley:. The preprocessing implementation was mentioned in the paper Sec. 4 (Ground-truth boundary maps and direction maps) and the previous issue [here](https://github.com/shenglandu/PushBoundary/issues/2). The preprocessing code for S3DIS used in the backbone KP-Conv is released [here](https://github.com/shenglandu/PushBoundary/blob/main/KPConv_Backbone/preprocessing_boundaries.py).


Best Regards,
Shenglan

**Comment by wu546300070** [comment]
Thank you for your enthusiastic and timely response!!

I would like to know how the S3DIS dataset for the pointnet++ network is constructed? You mention seems to be the dataset for the **kpconv network** and **preprocessing_boundaries.py** seems to process the .ply file rather than the .npy file, can you reveal more details about the construction of the dataset?

**Comment by shenglandu** [comment]
Hello,

For pre-processing .npy files it's similar. 
Step 1: obtain the raw s3dis .npy files.
This can be done following the official steps [here](https://github.com/yanx27/Pointnet_Pointnet2_pytorch#data-preparation-2).

Step 2: generate new .npy files with boundary and normal attributes.
This can be done by modifying the preprocessing [code](https://github.com/shenglandu/PushBoundary/blob/main/KPConv_Backbone/preprocessing_boundaries.py). You only need to modify the file reading and file writing part (L35, L41, L132-134). npy files can be read and written using np.load() and np.save(), see demos [here](https://numpy.org/doc/stable/reference/generated/numpy.load.html).


Best Regards,
Shenglan

**Comment by wu546300070** [comment]
Thanks again for your enthusiastic reply!
I made changes to the **preprocessing_boundaries.py** file based on the ideas you provided and it now processes npy files.

But the result seems to be different from your dataset (the first 2 lines of the same npy file, Area_1_conferenceRoom_1.npy), I hope to get your help, thanks again.❤️
![af30ca6cf62fc2632f974b975172497](https://github.com/shenglandu/PushBoundary/assets/42727019/d7517535-fe75-4e41-9340-71cc4daf3e9f)

**Comment by shenglandu** [comment]
Hello,

This is wired. As I can see, the order of points (in mine and in Yanxi's) is not the same. For example, the first 2 points from Yanxi's belong to category 8, while mine belong to category 7. I can look it up, check what went wrong in my released dataset, and also release the pre-processing code for S3DIS used in PointNet. (This will be done between mid-November and the end of November, sorry for the delay.)

Best Regards,
Shenglan

**Comment by wu546300070** [comment]
Thanks for your enthusiasm and looking forward to releasing your code!😊

**Comment by wu546300070** [comment]
The order in which preprocessing_boundaries.py writes the .npy data attributes is different from your S3DIS data, so I'm guessing that you may be missing the code to upload the pointnet++ branch data preprocessing file. I would be very grateful if you could resolve my query as soon as possible!      


The order of your dataset attributes is ['x', 'y', 'z', 'red', 'green', 'blue', **'class'**, 'nx', 'ny', 'nz', 'is_boundary', 'dx', 'dy', 'dz']

Whereas in the preprocessing_boundaries.py file ['x', 'y', 'z', 'red', 'green', 'blue', 'nx', 'ny', 'nz', 'is_boundary', 'dx', 'dy', 'dz', **'class'**]
![image](https://github.com/shenglandu/PushBoundary/assets/42727019/98398161-1ac2-4c5c-87c9-847a86e7815a)

**Comment by shenglandu** [comment]
> The order in which preprocessing_boundaries.py writes the .npy data attributes is different from your S3DIS data, so I'm guessing that you may be missing the code to upload the pointnet++ branch data preprocessing file. I would be very grateful if you could resolve my query as soon as possible!
> 
> The order of your dataset attributes is ['x', 'y', 'z', 'red', 'green', 'blue', **'class'**, 'nx', 'ny', 'nz', 'is_boundary', 'dx', 'dy', 'dz']
> 
> Whereas in the preprocessing_boundaries.py file ['x', 'y', 'z', 'red', 'green', 'blue', 'nx', 'ny', 'nz', 'is_boundary', 'dx', 'dy', 'dz', **'class'**] ![image](https://user-images.githubusercontent.com/42727019/274489130-98398161-1ac2-4c5c-87c9-847a86e7815a.png)

Hello there,

Sorry for the late response. I tried to look up at pre-processing this week but couldn't make it.  I will look it up as soon as possible after the deadline of my current project (~ mid-November). Sorry again for the delay :worried:.

Best Regards,
Shenglan

**Comment by wu546300070** [comment]
Thanks as always for your kind reply, looking forward to your updates👍😊

**Comment by wu546300070** [comment]
> > The order in which preprocessing_boundaries.py writes the .npy data attributes is different from your S3DIS data, so I'm guessing that you may be missing the code to upload the pointnet++ branch data preprocessing file. I would be very grateful if you could resolve my query as soon as possible!
> > The order of your dataset attributes is ['x', 'y', 'z', 'red', 'green', 'blue', **'class'**, 'nx', 'ny', 'nz', 'is_boundary', 'dx', 'dy', 'dz']
> > Whereas in the preprocessing_boundaries.py file ['x', 'y', 'z', 'red', 'green', 'blue', 'nx', 'ny', 'nz', 'is_boundary', 'dx', 'dy', 'dz', **'class'**] ![image](https://user-images.githubusercontent.com/42727019/274489130-98398161-1ac2-4c5c-87c9-847a86e7815a.png)
> 
> Hello there,
> 
> Sorry for the late response. I tried to look up at pre-processing this week but couldn't make it. I will look it up as soon as possible after the deadline of my current project (~ mid-November). Sorry again for the delay 😟.
> 
> Best Regards, Shenglan

Thanks as always for your kind reply, looking forward to your updates👍😊

**Comment by shenglandu** [comment]
> > > The order in which preprocessing_boundaries.py writes the .npy data attributes is different from your S3DIS data, so I'm guessing that you may be missing the code to upload the pointnet++ branch data preprocessing file. I would be very grateful if you could resolve my query as soon as possible!
> > > The order of your dataset attributes is ['x', 'y', 'z', 'red', 'green', 'blue', **'class'**, 'nx', 'ny', 'nz', 'is_boundary', 'dx', 'dy', 'dz']
> > > Whereas in the preprocessing_boundaries.py file ['x', 'y', 'z', 'red', 'green', 'blue', 'nx', 'ny', 'nz', 'is_boundary', 'dx', 'dy', 'dz', **'class'**] ![image](https://user-images.githubusercontent.com/42727019/274489130-98398161-1ac2-4c5c-87c9-847a86e7815a.png)
> > 
> > 
> > Hello there,
> > Sorry for the late response. I tried to look up at pre-processing this week but couldn't make it. I will look it up as soon as possible after the deadline of my current project (~ mid-November). Sorry again for the delay 😟.
> > Best Regards, Shenglan
> 
> Thanks as always for your kind reply, looking forward to your updates👍😊

Hi,

I have updated both the data (with the boundaries and directions) and the preprocessing code for the PointNet++ backbone. You can check the code under the directory of PointNet2_Backbone. The new data can still be accessed under the current link. 

Cheers,
Shenglan
