### ISSUE TITLE
您好，我有一些关于kpconv的问题想问您

### ISSUE THREAD

**Issue by sanfenzhongmeichifanle** [shenglandu/PushBoundary#9]
您对于sensaturban的数据集的数据预处理是在外部处理的吗？我看您的readme中是直接加载的该数据集预处理完成以后的数据？

**Comment by shenglandu** [comment]
> 您对于sensaturban的数据集的数据预处理是在外部处理的吗？我看您的readme中是直接加载的该数据集预处理完成以后的数据？

你好，由于SensatUrban原始数据量太大，我先进行了格网采样（20cm），然后在采样后的数据上进行预处理，包括计算边界和方向。处理的代码在[这里](https://github.com/shenglandu/PushBoundary/blob/main/KPConv_Backbone/preprocessing_boundaries.py)。

**Comment by sanfenzhongmeichifanle** [comment]
您好！谢谢您能回答我的问题，我看明白了。
第一个问题：您在SensatUrban_boundary.py，并没有进行相关预处理（比如kdtree文件的保存，索引文件保存等）。并且法向量、边界的计算保存等是在preprocessing_boundaries.py进行处理的是吗？
第二个问题:您发布的关于kpconv的这些内容适合window系统运行吗？，我的路径总是报错（抱歉，我是新手）
第三个问题：训练的过程中总是报这样的错误：
Model Preparation
*****************
Done in 0.7s


Start training
**************
e000-i0000 => L=4.935 acc=  5% bacc= 19% / t(ms): 57207.8 5085.2 143.4)
e000-i0015 => L=1.684 acc= 75% bacc= 98% / t(ms): 391.8 107.4 110.9)
e000-i0029 => L=1.919 acc= 44% bacc= 98% / t(ms): 477.2 108.8 107.4)
e000-i0044 => L=1.965 acc= 56% bacc= 98% / t(ms): 457.5 108.6 124.0)
e000-i0059 => L=1.439 acc= 40% bacc= 99% / t(ms): 471.0 108.9 110.8)
e000-i0074 => L=1.528 acc= 60% bacc= 99% / t(ms): 488.9 109.2 108.3)
e000-i0088 => L=1.507 acc= 57% bacc= 99% / t(ms): 401.4 112.5 198.3)
e000-i0103 => L=0.761 acc= 77% bacc=100% / t(ms): 463.2 112.2 127.2)
e000-i0117 => L=1.521 acc= 48% bacc= 99% / t(ms): 489.4 111.0 114.1)
e000-i0132 => L=1.110 acc= 68% bacc=100% / t(ms): 476.3 110.6 111.4)
e000-i0146 => L=1.741 acc= 49% bacc= 98% / t(ms): 494.8 111.9 110.2)
e000-i0161 => L=1.014 acc= 65% bacc= 99% / t(ms): 473.7 110.9 109.4)
e000-i0176 => L=1.018 acc= 68% bacc= 99% / t(ms): 478.5 109.4 107.9)
e000-i0190 => L=1.729 acc= 52% bacc= 99% / t(ms): 488.6 111.8 110.0)
e000-i0203 => L=1.014 acc= 85% bacc= 98% / t(ms): 414.0 113.8 343.2)
e000-i0219 => L=2.303 acc= 45% bacc= 97% / t(ms): 442.8 111.3 153.0)
e000-i0233 => L=2.007 acc= 41% bacc= 97% / t(ms): 456.0 113.5 138.7)
e000-i0248 => L=0.960 acc= 71% bacc= 99% / t(ms): 464.4 114.7 169.0)
e000-i0263 => L=1.326 acc= 69% bacc= 98% / t(ms): 468.3 113.0 122.5)
e000-i0278 => L=0.756 acc= 80% bacc= 99% / t(ms): 477.5 111.5 112.5)
e000-i0292 => L=0.735 acc= 90% bacc= 99% / t(ms): 488.1 113.5 112.8)
e000-i0307 => L=1.064 acc= 68% bacc= 98% / t(ms): 478.0 112.6 110.0)
e000-i0322 => L=1.676 acc= 66% bacc= 97% / t(ms): 481.6 108.6 108.1)
e000-i0337 => L=1.431 acc= 71% bacc= 97% / t(ms): 469.8 109.8 109.6)
e000-i0352 => L=1.258 acc= 67% bacc= 97% / t(ms): 471.7 111.1 110.9)
e000-i0367 => L=1.061 acc= 66% bacc= 99% / t(ms): 491.3 112.3 111.6)
e000-i0382 => L=0.764 acc= 92% bacc= 98% / t(ms): 485.6 112.3 112.4)
e000-i0396 => L=2.167 acc= 51% bacc= 97% / t(ms): 489.1 114.7 113.1)
e000-i0410 => L=0.853 acc= 87% bacc= 98% / t(ms): 482.8 112.2 117.9)
e000-i0423 => L=1.441 acc= 67% bacc= 96% / t(ms): 527.9 110.4 123.4)
e000-i0436 => L=1.960 acc= 60% bacc= 96% / t(ms): 546.1 112.7 113.3)
e000-i0450 => L=1.885 acc= 52% bacc= 98% / t(ms): 521.7 114.2 112.4)
e000-i0465 => L=1.741 acc= 54% bacc= 99% / t(ms): 478.4 108.3 107.1)
e000-i0479 => L=0.998 acc= 86% bacc= 98% / t(ms): 497.8 111.8 111.0)
e000-i0494 => L=0.889 acc= 70% bacc=100% / t(ms): 470.2 110.5 111.1)
e000-i0508 => L=1.478 acc= 56% bacc= 99% / t(ms): 485.5 111.0 111.5)
e000-i0523 => L=1.236 acc= 71% bacc= 98% / t(ms): 467.2 111.8 120.7)
e000-i0538 => L=1.115 acc= 76% bacc= 97% / t(ms): 459.1 111.9 112.4)
e000-i0553 => L=1.643 acc= 62% bacc= 98% / t(ms): 474.1 111.7 118.7)
e000-i0568 => L=2.630 acc= 41% bacc= 99% / t(ms): 473.9 111.1 112.0)
e000-i0582 => L=1.213 acc= 69% bacc= 98% / t(ms): 483.7 114.1 134.8)
e000-i0597 => L=0.719 acc= 78% bacc= 99% / t(ms): 492.3 110.8 114.1)
Traceback (most recent call last):
  File "F:\PushBoundary-main\KPConv_Backbone\train_SensatUrban_boundary.py", line 173, in <module>
    trainer.train(net, training_loader, test_loader, config)
  File "F:\PushBoundary-main\KPConv_Backbone\utils\trainer_boundary.py", line 170, in train
    self.cloud_segmentation_validation(net, val_loader, config)
  File "F:\PushBoundary-main\KPConv_Backbone\utils\trainer_boundary.py", line 212, in cloud_segmentation_validation
    for i, batch in enumerate(val_loader):
  File "C:\Users\403\anaconda3\envs\kpconv\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\Users\403\anaconda3\envs\kpconv\lib\site-packages\torch\utils\data\dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "C:\Users\403\anaconda3\envs\kpconv\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data
    data.reraise()
  File "C:\Users\403\anaconda3\envs\kpconv\lib\site-packages\torch\_utils.py", line 434, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\403\anaconda3\envs\kpconv\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\403\anaconda3\envs\kpconv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\403\anaconda3\envs\kpconv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\PushBoundary-main\KPConv_Backbone\datasets\SensatUrban_boundary.py", line 184, in __getitem__
    return self.potential_item(batch_i)
  File "F:\PushBoundary-main\KPConv_Backbone\datasets\SensatUrban_boundary.py", line 237, in potential_item
    cloud_ind = int(torch.argmin(self.min_potentials))
IndexError: argmin(): Expected reduction dim to be specified for input.numel() == 0.

![1](https://github.com/shenglandu/PushBoundary/assets/133829083/1016308d-7b2e-4227-aa1c-f2c1c8ef66cc)
您看一下我的路径是不是出问题了？
同时我发现一个问题，您看一下下面这个图片：
![image](https://github.com/shenglandu/PushBoundary/assets/133829083/fe718708-4560-4c85-ad82-ac43c3fa6fda)
就是用于测试的coarse索引文件怎么输入到了这个路径下面（F:\PushBoundary-main\KPConv_Backbone\data_sensat\input_0.200_train），我很是不解

同时，您如果方便的话，可以加一下微信吗？
非常非常感谢您，祝您假期愉快

**Comment by sanfenzhongmeichifanle** [comment]
您好，我的这个问题好像都解决了。因为之前我对您的代码进行了改动，可能出现了路径错误。
很抱歉打扰您了

**Comment by shenglandu** [comment]
> 您好，我的这个问题好像都解决了。因为之前我对您的代码进行了改动，可能出现了路径错误。 很抱歉打扰您了

没事没事，收到，祝好！

**Comment by sanfenzhongmeichifanle** [comment]
![image](https://github.com/shenglandu/PushBoundary/assets/133829083/81591553-1569-485c-8348-6447db464197)
您好，我的代码训练快结束的时候还是发生了错误，可是我的results文件夹并没有该路径下的文件。

**Comment by shenglandu** [comment]
> ![image](https://private-user-images.githubusercontent.com/133829083/327911879-81591553-1569-485c-8348-6447db464197.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MDc5OTYsIm5iZiI6MTcxNDgwNzY5NiwicGF0aCI6Ii8xMzM4MjkwODMvMzI3OTExODc5LTgxNTkxNTUzLTE1NjktNDg1Yy04MzQ4LTY0NDdkYjQ2NDE5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQwNzI4MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTFiOTgyMjMzZDdlOTkzNjU5OGVjY2JjYWJkNzQyNzQzMTViNGNkZGEwOTRlMzk0ZjdkZmU0MTBmZDRhMDNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9Uj8NqxQEql1OfEoSKbgePSGXpRP1tsiguAWhDpWnys) 您好，我的代码训练快结束的时候还是发生了错误，可是我的results文件夹并没有该路径下的文件。

你好，我觉得是路径问题，你可以手动指定一下trainer_boundary.py L315 的路径，不用os.join而直接指定路径。另外，你是在windows系统下跑的吗？我觉得你的validation mIoU没有我自己测试的时候高，不知道是不是因为系统的原因。如果修改后还有新的问题，我尽量在下周一左右回复你。
![image](https://github.com/shenglandu/PushBoundary/assets/33870342/a77dd4d1-021e-4ffe-a110-9d6077b8adcf)
